# Generated by Django 3.2.9 on 2021-11-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='lte_exists',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='release_date',
            field=models.DateTimeField(null=True),
        ),
    ]
